openapi: 3.0.2
info:
  title: faktura
  version: 1.0.0

tags:
  - name: faktura

paths:
  /account:
    get:
      tags:
        - faktura
      operationId: getAccounts
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountPage'
    post:
      tags:
        - faktura
      operationId: saveAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /account/{id}:
    get:
      tags:
        - faktura
      summary: Find by ID.
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          description: ID of entity
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      tags:
        - faktura
      summary: Deletes a entity.
      operationId: deleteAccount
      parameters:
        - name: id
          in: path
          description: Id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation

components:
  schemas:
    Pageable:
      description: Pageable query parameters
      type: object
      properties:
        pageNumber:
          type: integer
        pageSize:
          type: integer
    Page:
      description: Page response
      type: object
      properties:
        number:
          type: integer
        size:
          type: integer
    AccountPage:
      description: typed Page
      type: object
      allOf:
        - $ref: '#/components/schemas/Page'
        - $ref: '#/components/schemas/AccountList'
    AccountList:
      description: List of Accounts
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Account'
    Account:
      description: Account
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "Unique identifier for the account"
        description:
          type: string
          description: "Description of the account"
        noCharging:
          type: boolean
          description: "Indicates if charging is disabled"